"""Provider-neutral bounded orchestration contracts (no live provider SDK)."""

from .contracts import (
    AdvertisedTool,
    EvidenceProvenance,
    GenerationControls,
    LocalActionIdentity,
    ModelIdentifier,
    ProviderConfig,
    ProviderFinalMessage,
    ProviderMessage,
    ProviderRequest,
    ProviderToolCallProposal,
    RequestCorrelationId,
    RetryDecision,
    ToolCallId,
    new_request_correlation_id,
    parse_provider_response,
)
from .errors import ClassifiedFailure, FailureClass, ProviderError
from .limits import DEFAULT_LIMITS, Limits
from .mcp_orchestrator import (
    BoundedProvider,
    CancellationToken,
    McpStdioClient,
    OrchestrationOutcome,
    Orchestrator,
    ScriptedProvider,
)
from .openai_compatible import (
    OpenAICompatibleConfig,
    OpenAICompatibleProvider,
    OpenAICompatibleTransport,
    SyntheticFixture,
    openai_request_bytes,
    parse_openai_compatible_response,
    synthetic_fixture_message,
)

__all__ = [
    "DEFAULT_LIMITS",
    "AdvertisedTool",
    "BoundedProvider",
    "CancellationToken",
    "ClassifiedFailure",
    "EvidenceProvenance",
    "FailureClass",
    "GenerationControls",
    "Limits",
    "LocalActionIdentity",
    "McpStdioClient",
    "ModelIdentifier",
    "OpenAICompatibleConfig",
    "OpenAICompatibleProvider",
    "OpenAICompatibleTransport",
    "OrchestrationOutcome",
    "Orchestrator",
    "ProviderConfig",
    "ProviderError",
    "ProviderFinalMessage",
    "ProviderMessage",
    "ProviderRequest",
    "ProviderToolCallProposal",
    "RequestCorrelationId",
    "RetryDecision",
    "ScriptedProvider",
    "SyntheticFixture",
    "ToolCallId",
    "new_request_correlation_id",
    "openai_request_bytes",
    "parse_openai_compatible_response",
    "parse_provider_response",
    "synthetic_fixture_message",
]
